version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/project/src
      - ./public:/project/public
    environment:
      - CHOKIDAR_USEPOLLING=true
